name = "rebuildshownotesfilter"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-11-27"

[site]
bucket = "out"
entry-point = "./"
